Header:
    version: 151
Prototypes:
-   class: "UIControl"
    name: "TankRankIcon"
    input: false
    components:
        Background:
            drawType: "DRAW_STRETCH_BOTH"
        SizePolicy:
            horizontalPolicy: "FixedSize"
            horizontalValue: 220.000000
            verticalPolicy: "FixedSize"
            verticalValue: 220.000000
        UIDataParamsComponent:
            params:
            - ["eTankRankGrade", "grade", "eTankRankGrade.Legendary", "eTankRankGrade.Unique"]
            - ["int", "rank", "0", "10"]
        UIDataLocalBindingsComponent:
            data:
            - ["string", "icon", "\"~res:/Gfx/Lobby/backgrounds/tank-rank/\" + str(grade, eTankRankGrade, \"icon\") + \"_l\""]
        UIIdentifierComponent:
            id: "big_rank_icon"
            params:
            - ["string", "rank_grade", "str(grade, eTankRankGrade)"]
            - ["int", "rank_level", "rank"]
    bindings:
    - ["Background.sprite", "icon"]
    children:
    -   class: "UIControl"
        name: "Rank"
        input: false
        classes: "white-wild-sand-text"
        components:
            Anchor:
                hCenterAnchorEnabled: true
                vCenterAnchorEnabled: true
                vCenterAnchor: -24.000000
            UITextComponent:
                fontPath: "~res:/Fonts/AVICII.ttf"
                fontSize: 90.000000
                align: ["HCENTER", "VCENTER"]
                perPixelAccuracyType: "PER_PIXEL_ACCURACY_FORCED"
            UIShadowComponent:
                blurType: "Gauss"
                indent: 16
                canBeDelayed: true
            SizePolicy:
                horizontalPolicy: "PercentOfContent"
                verticalPolicy: "PercentOfContent"
            StyleSheet:
                styles: "~res:/UI/Screens3/Color.style.yaml"
        bindings:
        - ["UITextComponent.text", "str(rank)"]
        - ["UIShadowComponent.color", "when rank >= 40 -> rgba(255, 215, 0, 1.000000), rank >= 30 -> rgba(153, 138, 230, 1.000000), rank >= 20 -> rgba(115, 209, 255, 1.000000), rank >= 10 -> rgba(168, 230, 138, 1.000000), rgba(245, 245, 245, 1.000000)"]
